#!/usr/bin/expect -f

set server [lindex $argv 0];

if {[llength $argv] == 0} {
  send_user "Usage: scriptname server_nick\n"
  exit 1
}

send_user "\n#####\n# $server\n#####\n"

if { $server == "my_server" } { 
    	spawn ssh -p 12345 username@hostname
	expect {
	  timeout { send_user "\nFailed to get password prompt\n"; exit 1 }
	  eof { send_user "\nSSH failure for $server\n"; exit 1 }
	  "*assword"
	}
	set password "pAsSwOrD"
	send "$password\r"

	expect {
	  timeout { send_user "\nLogin failed. Password incorrect.\n"; exit 1}
	  "*\$ "
	}
	interact

} elseif { $server == "someone_elses_server" } { 
	spawn ssh -p 12345 username@hostname
	expect {
	  timeout { send_user "\nFailed to get password prompt\n"; exit 1 }
	  eof { send_user "\nSSH failure for $server\n"; exit 1 }
	  "*assword"
	}
	set password "pAsSwOrD"
	send "$password\r"

	expect {
	  timeout { send_user "\nLogin failed. Password incorrect.\n"; exit 1}
	  "*\$ "
	}
	interact
} else { 
    send_user "Can\'t Recognize Server!\n" 
}
